FROM debian:12.6-slim
VOLUME /cache
RUN apt-get update && apt-get install -y ca-certificates && \
    adduser -D -u 1000 -g 1000 -h /home/k6exec k6exec && \
    mkdir -p /cache/k6exec && \
    chown -R 1000:1000 /cache && \
    ln -s /usr/bin/k6exec /usr/bin/k6
ENV CGO_ENABLED=1 XDG_CACHE_HOME="/cache"
COPY k6exec /usr/bin/k6exec

USER 1000
WORKDIR /home/k6exec
ENTRYPOINT ["k6exec"]
