#!/bin/bash

export TAG="$1"

if [ -z "$TAG" ]; then
  echo "Usage: getk6 version-tag" >&2
  exit 1
fi

export BASE="cmd/k6exec/k6"
export DISTRO="grafana/k6"
export OS_LIST=("linux" "darwin" "windows")
export ARCH_LIST=("amd64" "arm64")

download() {
    local os="$1"
    local arch="$2"
    local platform="${os}/${arch}"
    local target="${BASE}/${platform}"
    local asset=".zip"
    if [ "$os" == "linux" ]; then
      asset=".tar.gz"
    fi
    if [ "$os" == "windows" ]; then
      ext=".exe"
    fi
 
    mkdir -p "${target}"
    eget --tag="${TAG}" --to "${target}" -s "${platform}" --asset="${asset}" "${DISTRO}"
    pushd "${target}"
    shasum --algorithm 256 --binary "k6${ext}" | cut -f1 -d ' ' > "sha256.txt"
    echo -n "${TAG}" > version.txt
    popd
}

compress() {
    local os="$1"
    local arch="$2"
    local platform="${os}/${arch}"
    local target="${BASE}/${platform}"
    local ext=""
    if [ "$os" == "windows" ]; then
      ext=".exe"
    fi
    local exe="${target}/k6${ext}"

    gzip --force --best "${exe}"
}

for OS in ${OS_LIST[*]}; do
  for ARCH in ${ARCH_LIST[*]}; do
    download "${OS}" "${ARCH}"
    compress "${OS}" "${ARCH}"
  done
done
