name: lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - README.md
      - "releases/**"

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: v1.62.2
          args: --timeout=30m
          install-mode: binary
