name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      EGET_DIR: ${{github.workspace}}/.eget
      EGET_CONFIG: ${{github.workspace}}/.eget/.eget.toml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Setup eget
        shell: bash
        run: |
          curl https://zyedidia.github.io/eget.sh | sh
          mkdir -p $EGET_DIR && mv eget $EGET_DIR
          DIR=$(readlink -f $EGET_DIR) # workaround for windows + toml
          printf "[global]\ntarget='$DIR'\nquiet=true\ngithub_token='${{ github.token }}'\n" > $EGET_CONFIG
          echo $EGET_DIR >> $GITHUB_PATH
          echo "EGET_CONFIG=$EGET_CONFIG" >> $GITHUB_ENV
      - name: Download k6
        run: ./tools/getk6 $(< k6-version.txt)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "amd64,arm64"
      - name: Login to GitHub packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "2.4.7"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
