name: test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - README.md
      - "releases/**"

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    env:
      REGISTRY: ghcr.io
      EGET_DIR: ${{github.workspace}}/.eget
      EGET_CONFIG: ${{github.workspace}}/.eget/.eget.toml
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup eget
        run: |
          if test -f $EGET_CONFIG; then
            exit 0
          fi

          curl https://zyedidia.github.io/eget.sh | sh
          mkdir -p $EGET_DIR && mv eget $EGET_DIR
          DIR=$(readlink -f $EGET_DIR) # workaround for windows + toml
          printf "[global]\ntarget='$DIR'\nquiet=true\ngithub_token='${{ github.token }}'\n" > $EGET_CONFIG
          echo $EGET_DIR >> $GITHUB_PATH
          echo "EGET_CONFIG=$EGET_CONFIG" >> $GITHUB_ENV
      - name: Download k6
        run: ./tools/getk6

      - name: Test
        run: go test -race -count 1 ./...

      - name: Coverage Test
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'main' }}
        run: go test -count 1 -coverprofile=coverage.txt ./...
      - name: Upload Coverage
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'main' }}
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: grafana/k6exec

      - name: Generate Go Report Card
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'main' }}
        uses: creekorful/goreportcard-action@v1.0
